/* chat_embed.h - generated */
#ifndef CHAT_EMBED_H
#define CHAT_EMBED_H
static const char CHAT_HTML[] =
  "<!DOCTYPE html>\n"
  "<html lang=\"zh\">\n"
  "<head>\n"
  "<meta charset=\"utf-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
  "<title>Infiverse \350\201\212\345\244\251</title>\n"
  "<style>\n"
  "* { margin:0; padding:0; box-sizing:border-box; }\n"
  "html,body { height:100%; overflow:hidden; font-family:system-ui,\"Microsoft YaHei\",sans-serif; background:#0e1220; color:#e6edf3; }\n"
  "#app { display:flex; height:100vh; }\n"
  "#side { width:240px; min-width:240px; background:#151b2c; border-right:1px solid #232c42; display:flex; flex-direction:column; }\n"
  "#sideHead { padding:14px; border-bottom:1px solid #1f2838; display:flex; justify-content:space-between; align-items:center; }\n"
  "#sideHead h1 { font-size:15px; color:#7fd4ff; }\n"
  "#sideHead button { background:#2563eb; color:#fff; border:none; border-radius:6px; padding:5px 10px; cursor:pointer; font-size:12px; }\n"
  "#flist { flex:1; overflow-y:auto; }\n"
  ".f { display:flex; align-items:center; gap:10px; padding:11px 14px; cursor:pointer; border-bottom:1px solid #1a2134; }\n"
  ".f:hover { background:#1d2638; }\n"
  ".f.active { background:#22304f; }\n"
  ".f .av { width:34px; height:34px; border-radius:8px; display:flex; align-items:center; justify-content:center; font-size:16px; color:#fff; flex-shrink:0; }\n"
  ".f .nm { flex:1; min-width:0; }\n"
  ".f .nm .n { font-size:13px; }\n"
  ".f .nm .s { font-size:11px; color:#7d8aa5; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }\n"
  ".f .ai { font-size:10px; background:#7c3aed; color:#fff; padding:1px 6px; border-radius:8px; }\n"
  "#main { flex:1; display:flex; flex-direction:column; }\n"
  "#chatHead { padding:12px 16px; border-bottom:1px solid #1f2838; font-size:14px; font-weight:600; }\n"
  "#chatBox { flex:1; overflow-y:auto; padding:14px; display:flex; flex-direction:column; gap:8px; }\n"
  ".m { max-width:70%; padding:8px 12px; border-radius:10px; font-size:13px; line-height:1.5; word-break:break-word; }\n"
  ".m.me { align-self:flex-end; background:#2563eb; color:#fff; }\n"
  ".m.other { align-self:flex-start; background:#1d2337; border:1px solid #2a3350; }\n"
  ".m .tm { font-size:10px; color:#7d8aa5; margin-top:3px; text-align:right; }\n"
  "#inputRow { display:flex; gap:8px; padding:12px; border-top:1px solid #1f2838; }\n"
  "#chatText { flex:1; background:#151b2c; color:#e6edf3; border:1px solid #2a3350; border-radius:8px; padding:10px; font-size:13px; outline:none; }\n"
  "#sendBtn { background:#2563eb; color:#fff; border:none; border-radius:8px; padding:0 20px; cursor:pointer; font-size:13px; }\n"
  "#addBox { display:none; padding:10px 14px; border-bottom:1px solid #1f2838; background:#101625; }\n"
  "#addBox input { background:#151b2c; border:1px solid #2a3350; border-radius:6px; padding:7px; color:#e6edf3; margin:3px 0; width:100%; font-size:12px; }\n"
  "#addBox button { background:#1f7a4d; color:#fff; border:none; border-radius:6px; padding:6px; width:100%; cursor:pointer; font-size:12px; margin-top:4px; }\n"
  ".empty { color:#5d6b84; font-size:13px; padding:30px; text-align:center; }\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div id=\"app\">\n"
  "  <div id=\"side\">\n"
  "    <div id=\"sideHead\"><h1>&#128172; \350\201\212\345\244\251</h1><button onclick=\"toggleAdd()\">+ \345\245\275\345\217\213</button></div>\n"
  "    <div id=\"addBox\">\n"
  "      <input id=\"fName\" placeholder=\"\345\220\215\345\255\227\">\n"
  "      <input id=\"fId\" placeholder=\"ID (u_...) \346\210\226 \350\212\202\347\202\271IP:u_id\">\n"
  "      <button onclick=\"addFriend()\">\346\267\273\345\212\240</button>\n"
  "    </div>\n"
  "    <div id=\"flist\"></div>\n"
  "  </div>\n"
  "  <div id=\"main\">\n"
  "    <div id=\"chatHead\">\351\200\211\346\213\251\344\270\200\344\270\252\345\245\275\345\217\213\345\274\200\345\247\213\350\201\212\345\244\251</div>\n"
  "    <div id=\"chatBox\"><div class=\"empty\">\344\273\216\345\267\246\344\276\247\351\200\211\346\213\251\345\245\275\345\217\213,\346\210\226\346\267\273\345\212\240\346\226\260\345\245\275\345\217\213</div></div>\n"
  "    <div id=\"inputRow\" style=\"display:none\">\n"
  "      <input id=\"chatText\" placeholder=\"\350\276\223\345\205\245\346\266\210\346\201\257,\345\233\236\350\275\246\345\217\221\351\200\201\">\n"
  "      <button id=\"sendBtn\" onclick=\"sendChat()\">\345\217\221\351\200\201</button>\n"
  "    </div>\n"
  "  </div>\n"
  "</div>\n"
  "<script>\n"
  "var cur = '', curName = '', lastCount = -1;\n"
  "function $(id){ return document.getElementById(id); }\n"
  "function esc(s){ return (''+s).replace(/&/g,'&amp;').replace(/</g,'&lt;'); }\n"
  "function toggleAdd(){ var b = $('addBox'); b.style.display = b.style.display === 'none' ? 'block' : 'none'; }\n"
  "function addFriend(){\n"
  "  var id = $('fId').value.trim(), nm = $('fName').value.trim();\n"
  "  if (!id) return;\n"
  "  var node = '';\n"
  "  if (id.indexOf('@') > 0) { var sp = id.split('@'); id = sp[0]; node = sp[1]; }\n"
  "  fetch('/api/friend?name=' + encodeURIComponent(nm || id) + '&id=' + encodeURIComponent(id) + (node ? '&node=' + encodeURIComponent(node) : '')).then(function(r){ return r.json(); }).then(function(){ $('fId').value=''; $('fName').value=''; loadList(); });\n"
  "}\n"
  "function loadList(){\n"
  "  Promise.all([fetch('/api/friends').then(function(r){ return r.json(); }).catch(function(){ return {friends:[]}; }),\n"
  "               fetch('/api/ai').then(function(r){ return r.json(); }).catch(function(){ return {ais:[]}; })])\n"
  "    .then(function(res){\n"
  "      var fs = res[0].friends || [], ais = res[1].ais || [];\n"
  "      var h = '';\n"
  "      fs.forEach(function(f){\n"
  "        var isAI = f.is_ai === 1 || f.is_ai === true;\n"
  "        var av = (f.name || '?').charAt(0);\n"
  "        h += '<div class=\"f' + (cur === f.id ? ' active' : '') + '\" onclick=\"openChat(\\'' + f.id + '\\',\\'' + esc(f.name) + '\\')\">'\n"
  "           + '<div class=\"av\" style=\"background:' + (isAI ? '#7c3aed' : '#2b7fff') + '\">' + esc(av) + '</div>'\n"
  "           + '<div class=\"nm\"><div class=\"n\">' + esc(f.name) + (isAI ? ' <span class=\"ai\">AI</span>' : '') + '</div><div class=\"s\">' + esc(f.id) + '</div></div></div>';\n"
  "      });\n"
  "      ais.forEach(function(a){\n"
  "        var h2 = '<div class=\"f' + (cur === a.id ? ' active' : '') + '\" onclick=\"openChat(\\'' + a.id + '\\',\\'' + esc(a.name) + '\\')\">'\n"
  "           + '<div class=\"av\" style=\"background:#7c3aed\">' + esc((a.name || '?').charAt(0)) + '</div>'\n"
  "           + '<div class=\"nm\"><div class=\"n\">' + esc(a.name) + ' <span class=\"ai\">AI</span></div><div class=\"s\">' + esc(a.id) + '</div></div></div>';\n"
  "        h += h2;\n"
  "      });\n"
  "      $('flist').innerHTML = h || '<div class=\"empty\">\346\232\202\346\227\240\345\245\275\345\217\213</div>';\n"
  "    });\n"
  "}\n"
  "function openChat(id, name){\n"
  "  cur = id; curName = name; lastCount = -1;\n"
  "  $('chatHead').textContent = '\344\270\216 ' + name + ' \350\201\212\345\244\251';\n"
  "  $('inputRow').style.display = 'flex';\n"
  "  loadChat();\n"
  "  loadList();\n"
  "}\n"
  "function loadChat(){\n"
  "  if (!cur) return;\n"
  "  fetch('/api/chat?peer=' + encodeURIComponent(cur)).then(function(r){ return r.json(); }).then(function(j){\n"
  "    var msgs = j.msgs || [];\n"
  "    if (msgs.length === lastCount && $('chatBox').innerHTML !== '') return;\n"
  "    lastCount = msgs.length;\n"
  "    var h = '';\n"
  "    msgs.forEach(function(m){\n"
  "      var mine = m.from === 'me';\n"
  "      h += '<div class=\"m ' + (mine ? 'me' : 'other') + '\">' + esc(m.text)\n"
  "         + '<div class=\"tm\">' + new Date((m.ts || 0) * 1000).toLocaleString() + '</div></div>';\n"
  "    });\n"
  "    $('chatBox').innerHTML = h || '<div class=\"empty\">\350\277\230\346\262\241\346\234\211\346\266\210\346\201\257</div>';\n"
  "    $('chatBox').scrollTop = $('chatBox').scrollHeight;\n"
  "  }).catch(function(){});\n"
  "}\n"
  "function sendChat(){\n"
  "  var t = $('chatText').value.trim();\n"
  "  if (!t || !cur) return;\n"
  "  fetch('/api/chat?peer=' + encodeURIComponent(cur) + '&text=' + encodeURIComponent(t), {method:'POST'}).then(function(r){ return r.json(); }).then(function(){\n"
  "    $('chatText').value = '';\n"
  "    lastCount = -1;\n"
  "    loadChat();\n"
  "  });\n"
  "}\n"
  "$('chatText').addEventListener('keydown', function(e){ if (e.key === 'Enter') sendChat(); });\n"
  "setInterval(function(){ if (cur) loadChat(); }, 2500);\n"
  "loadList();\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
  "\n"
  "";
#endif
