/* desktop_embed.h - generated */
#ifndef DESKTOP_EMBED_H
#define DESKTOP_EMBED_H
static const char DESKTOP_HTML[] =
  "<!DOCTYPE html>\n"
  "<html lang=\"zh\">\n"
  "<head>\n"
  "<meta charset=\"utf-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
  "<title>Infiverse \346\241\214\351\235\242</title>\n"
  "<style>\n"
  "* { margin:0; padding:0; box-sizing:border-box; }\n"
  "html,body { height:100%; overflow:hidden; font-family:system-ui,\"Microsoft YaHei\",sans-serif; background:#0d1117; color:#e6edf3; }\n"
  "#app { display:flex; height:100vh; }\n"
  "/* ---- left sidebar (like instant messengers) ---- */\n"
  "#side { width:232px; min-width:232px; background:#141a26; border-right:1px solid #232c3d; display:flex; flex-direction:column; }\n"
  "#me { display:flex; align-items:center; gap:10px; padding:16px 14px; border-bottom:1px solid #1f2838; }\n"
  "#avatar { width:42px; height:42px; border-radius:10px; background:linear-gradient(135deg,#2b7fff,#5ee7a0); display:flex; align-items:center; justify-content:center; font-size:22px; color:#fff; }\n"
  "#meInfo { min-width:0; }\n"
  "#myName { font-size:14px; font-weight:600; color:#f0f4fa; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }\n"
  "#myId { font-size:11px; color:#7d8aa5; margin-top:2px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }\n"
  "#nav { flex:1; padding:10px 8px; overflow-y:auto; }\n"
  ".nav-item { display:flex; align-items:center; gap:10px; padding:11px 12px; margin-bottom:4px; border-radius:8px; color:#b8c3d6; font-size:14px; cursor:pointer; transition:background .12s; }\n"
  ".nav-item:hover { background:#1d2638; color:#e6edf3; }\n"
  ".nav-item.active { background:#2563eb; color:#fff; }\n"
  ".nav-item .ico { width:22px; text-align:center; font-size:16px; }\n"
  "#sideFoot { padding:12px 14px; border-top:1px solid #1f2838; font-size:11px; color:#5d6b84; }\n"
  "#sideFoot .dot { display:inline-block; width:8px; height:8px; border-radius:50%; background:#3ddc84; margin-right:6px; vertical-align:middle; }\n"
  "/* ---- content ---- */\n"
  "#main { flex:1; display:flex; flex-direction:column; background:#0d1117; }\n"
  "#status { height:30px; min-height:30px; background:#101623; border-bottom:1px solid #1f2838; display:flex; align-items:center; padding:0 14px; font-size:12px; color:#8b98b2; gap:16px; }\n"
  "#status .ok { color:#3ddc84; }\n"
  "#status button { background:none; border:none; color:#8b98b2; cursor:pointer; font-size:12px; padding:0 4px; }\n"
  "#frameBox { flex:1; }\n"
  "#frameBox iframe { width:100%; height:100%; border:0; background:#0d1117; }\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div id=\"app\">\n"
  "  <div id=\"side\">\n"
  "    <div id=\"me\">\n"
  "      <div id=\"avatar\">?</div>\n"
  "      <div id=\"meInfo\"><div id=\"myName\">\345\212\240\350\275\275\344\270\255...</div><div id=\"myId\">-</div></div>\n"
  "    </div>\n"
  "    <div id=\"nav\">\n"
  "      <div class=\"nav-item active\" data-u=\"home\"><span class=\"ico\">&#128100;</span>\344\270\252\344\272\272\344\270\273\351\241\265</div>\n"
  "      <div class=\"nav-item\" data-u=\"chat\"><span class=\"ico\">&#128172;</span>\350\201\212\345\244\251</div>\n"
  "      <div class=\"nav-item\" data-u=\"netplay\"><span class=\"ico\">&#128225;</span>\350\201\224\346\234\272</div>\n"
  "      <div class=\"nav-item\" data-u=\"forge\"><span class=\"ico\">&#128295;</span>Forge</div>\n"
  "      <div class=\"nav-item\" data-u=\"wb\"><span class=\"ico\">&#128193;</span>\345\267\245\344\275\234\345\217\260</div>\n"
  "    </div>\n"
  "    <div id=\"sideFoot\"><span class=\"dot\"></span>\346\234\215\345\212\241\350\277\220\350\241\214\344\270\255</div>\n"
  "  </div>\n"
  "  <div id=\"main\">\n"
  "    <div id=\"status\"><span class=\"ok\">&#9679; Infiverse</span><span id=\"ip\">-</span><button id=\"copyIpBtn\" onclick=\"copyIp()\" title=\"\0156IP\">=\313</button></div>\n"
  "    <div id=\"frameBox\"><iframe id=\"f\" src=\"/home\"></iframe></div>\n"
  "  </div>\n"
  "</div>\n"
  "<script>\n"
  "var pages = { home:'/home', chat:'/chat', netplay:'/netplay', forge:'/forge', wb:'/wb' };\n"
  "function setPage(u){\n"
  "  var f = document.getElementById('f');\n"
  "  f.src = pages[u] || '/home';\n"
  "  document.querySelectorAll('.nav-item').forEach(function(n){ n.classList.toggle('active', n.getAttribute('data-u') === u); });\n"
  "}\n"
  "document.querySelectorAll('.nav-item').forEach(function(n){\n"
  "  n.addEventListener('click', function(){ setPage(n.getAttribute('data-u')); });\n"
  "});\n"
  "fetch('/ip').then(function(r){ return r.text(); }).then(function(t){\n"
  "  document.getElementById('ip').textContent = t.trim();\n"
  "}).catch(function(){});\n"
  "fetch('/api/me').then(function(r){ return r.json(); }).then(function(j){\n"
  "  if(j && j.name){ document.getElementById('myName').textContent = j.name; document.getElementById('myId').textContent = j.id || ''; document.getElementById('avatar').textContent = (j.avatar || j.name || '?').charAt(0); }\n"
  "}).catch(function(){});\n"
  "\n"
  "function copyIp(){\n"
  "  var t = (document.getElementById('ip').textContent || '').trim();\n"
  "  if (!t) return;\n"
  "  var ok = function(){ var o = document.getElementById('copyIpBtn'); if (o) o.textContent = '\\u2713'; setTimeout(function(){ if (o) o.textContent = '\\uD83D\\uDCCB'; }, 1200); };\n"
  "  if (navigator.clipboard && navigator.clipboard.writeText) { navigator.clipboard.writeText(t).then(ok); }\n"
  "  else { var ta = document.createElement('textarea'); ta.value = t; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); document.body.removeChild(ta); ok(); }\n"
  "}\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
  "\n"
  "";
#endif
