/* bridge_jni.c - JNI side of the generated InimerseBridge facade.
 *
 * The Java class is generated by tools/bindgen.py from
 * src/bridge/inimerse_bridge.def (interface inimerse_bridge -> class
 * InimerseBridge, native methods native_version / native_sha256_file /
 * native_parse_count).  This file supplies those natives and binds them with
 * RegisterNatives from JNI_OnLoad, so no C symbol has to encode the JNI name
 * mangling of the generated method names.
 *
 * Every native calls the same C ABI (bridge_abi.c) the CPython extension calls,
 * which is what makes the Java and Python sides print identical values.
 */
#include <jni.h>
#include <stdio.h>
#include <string.h>

#include "inimerse_bridge.h"

/* Raise the facade's own checked exception, falling back to
 * RuntimeException if the class cannot be resolved. */
static void throw_bridge(JNIEnv *env, const char *fn, int code) {
    char msg[256];
    jclass ex;
    jmethodID ctor;
    jstring jmsg;
    jobject obj;

    snprintf(msg, sizeof msg, "inimerse bridge: %s failed (code %d)", fn, code);

    ex = (*env)->FindClass(env, "InimerseBridge$InimerseException");
    if (ex) {
        ctor = (*env)->GetMethodID(env, ex, "<init>", "(ILjava/lang/String;)V");
        if (ctor) {
            jmsg = (*env)->NewStringUTF(env, msg);
            if (jmsg) {
                obj = (*env)->NewObject(env, ex, ctor, (jint)code, jmsg);
                if (obj) {
                    (*env)->Throw(env, (jthrowable)obj);
                    (*env)->DeleteLocalRef(env, obj);
                }
                (*env)->DeleteLocalRef(env, jmsg);
            }
            return;
        }
    }
    (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/RuntimeException"), msg);
}

static jstring to_jstring(JNIEnv *env, const char *s, size_t len) {
    return (*env)->NewStringUTF(env, s); /* ABI strings are ASCII (version, hex) */
}

static jstring JNICALL native_version(JNIEnv *env, jclass cls) {
    const char *out = NULL;
    size_t len = 0;
    (void)cls;
    if (inimerse_bridge_version(&out, &len) != 0) {
        throw_bridge(env, "version", 1);
        return NULL;
    }
    return to_jstring(env, out, len);
}

static jstring JNICALL native_sha256_file(JNIEnv *env, jclass cls, jstring path) {
    const char *out = NULL;
    size_t len = 0;
    const char *p;
    int rc;
    (void)cls;
    if (!path) {
        throw_bridge(env, "sha256_file", 1);
        return NULL;
    }
    p = (*env)->GetStringUTFChars(env, path, NULL);
    if (!p) return NULL;
    rc = inimerse_bridge_sha256_file(p, strlen(p), &out, &len);
    (*env)->ReleaseStringUTFChars(env, path, p);
    if (rc != 0) {
        throw_bridge(env, "sha256_file", rc);
        return NULL;
    }
    return to_jstring(env, out, len);
}

static jint JNICALL native_parse_count(JNIEnv *env, jclass cls, jstring source) {
    const char *s;
    size_t len;
    int32_t out = 0;
    int rc;
    (void)cls;
    if (!source) {
        throw_bridge(env, "parse_count", 1);
        return 0;
    }
    s = (*env)->GetStringUTFChars(env, source, NULL);
    if (!s) return 0;
    len = strlen(s);
    rc = inimerse_bridge_parse_count(s, len, &out);
    (*env)->ReleaseStringUTFChars(env, source, s);
    if (rc != 0) {
        throw_bridge(env, "parse_count", rc);
        return 0;
    }
    return (jint)out;
}

static const JNINativeMethod kMethods[] = {
    {"native_version", "()Ljava/lang/String;", (void *)native_version},
    {"native_sha256_file", "(Ljava/lang/String;)Ljava/lang/String;", (void *)native_sha256_file},
    {"native_parse_count", "(Ljava/lang/String;)I", (void *)native_parse_count},
};

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env = NULL;
    jclass cls;
    (void)reserved;

    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_8) != JNI_OK) return JNI_ERR;
    cls = (*env)->FindClass(env, "InimerseBridge");
    if (!cls) return JNI_ERR;
    if ((*env)->RegisterNatives(env, cls, kMethods,
                                (jint)(sizeof kMethods / sizeof kMethods[0])) != JNI_OK)
        return JNI_ERR;
    return JNI_VERSION_1_8;
}
