#ifndef LEXER_H
#define LEXER_H

#include "common.h"

typedef enum {
    TOK_USING, TOK_WINDOW, TOK_SHOW, TOK_HIDE, TOK_AT, TOK_LAYER,
    TOK_NEW, TOK_BLOCK, TOK_THREAD, TOK_TASK, TOK_ON, TOK_START,
    TOK_IF, TOK_ELIF, TOK_ELSE, TOK_WHILE, TOK_FOR, TOK_REPEAT, TOK_IN, TOK_UNLESS,
    TOK_UNTIL, TOK_DO, TOK_BREAK,
    TOK_WAIT, TOK_STOP, TOK_YIELD, TOK_ALL, TOK_SAY, TOK_CURSOR,
    TOK_INT, TOK_FLOAT, TOK_STR, TOK_BOOL, TOK_ARRAY,
    TOK_TRUE, TOK_FALSE, TOK_INCLUDE, TOK_DELETE, TOK_THIS,
    TOK_FUNC, TOK_RETURN,
    TOK_IMPORT, TOK_AS, TOK_MAIN, TOK_GLOBAL,
    TOK_PAUSE, TOK_RESUME, TOK_KILL, TOK_JOIN,
    TOK_LOCK, TOK_UNLOCK, TOK_SEND, TOK_RECV,
    TOK_STAGE, TOK_BACKGROUND, TOK_SPRITE, TOK_GOTO, TOK_MOVE,
    TOK_BOX, TOK_COSTUME, TOK_FACE, TOK_TURN, TOK_POINT_TO,
    TOK_VELOCITY, TOK_GRAVITY, TOK_BOUNCE, TOK_SIZE,
    TOK_SOUND, TOK_MUSIC, TOK_TEXT, TOK_BROADCAST,
    TOK_CLONE, TOK_FOREVER, TOK_WHEN,
    TOK_IDENT, TOK_NUMBER, TOK_STRING, TOK_FSTRING,
    TOK_PLUS, TOK_MINUS, TOK_STAR, TOK_SLASH, TOK_PERCENT,
    TOK_EQ, TOK_EQEQ, TOK_NEQ, TOK_LT, TOK_GT, TOK_LE, TOK_GE,
    TOK_AND, TOK_OR, TOK_NOT,
    TOK_LPAREN, TOK_RPAREN, TOK_LBRACKET, TOK_RBRACKET,
    TOK_LBRACE, TOK_RBRACE, TOK_COLON, TOK_SEMI, TOK_COMMA,
    TOK_DOT, TOK_RANGE,
    TOK_ARROW, TOK_DECLARE, TOK_CASE, TOK_RECORD, TOK_WITH, TOK_CONST, TOK_AUTOSAVE, TOK_QUIT_ON_ESCAPE, TOK_FULLSCREEN, TOK_FIXED, TOK_GHOST, TOK_CLICKABLE, TOK_DRAG, TOK_SECRET, TOK_TAG,
    TOK_PLUS_EQ, TOK_MINUS_EQ, TOK_STAR_EQ, TOK_SLASH_EQ,
    TOK_ENDLESS, TOK_DAEMON, TOK_RESTART, TOK_SINGLE,
    TOK_TILDE, TOK_BE /* 保留字墓碑：构造已移除，词法保留的理由见 lexer.c:43 */, TOK_TYPE, TOK_MIN, TOK_MAX,
    TOK_TRY, TOK_CATCH, TOK_THROW,
    TOK_PIPE, TOK_PIPELINE, TOK_COMPOSE, TOK_QUESTION,
    TOK_FINAL, TOK_MATCH,
    TOK_EOF, TOK_UNKNOWN
,
    TOK_CONTINUE, TOK_TO,
    TOK_PLUS_PLUS, TOK_MINUS_MINUS
} InimerseTokenType;

/* 线程操作枚举（供 parser/compiler 共享�?*/
typedef enum {
    THREAD_OP_STOP = 0,
    THREAD_OP_PAUSE = 1,
    THREAD_OP_RESUME = 2,
    THREAD_OP_KILL = 3,
    THREAD_OP_RESTART = 4
} ThreadOp;

typedef struct {
    InimerseTokenType type;
    StringView text;
    union {
        int64_t intVal;
        double floatVal;
        bool boolVal;
    };
} Token;

typedef struct {
    const char *src;
    int pos;
    int line;
    int col;
    Token current;
    char *strbuf;   /* lIU �(W&2+͜`�() */
    int strcap;
} Lexer;

void lexer_init(Lexer *lex, const char *source);
Token lexer_next(Lexer *lex);
Token lexer_peek(Lexer *lex);

#endif
