#!/usr/bin/env python3
"""Unified IDL / binding generator (v0.5 roadmap §3.4).

One interface definition drives C/C++, Java and Python bindings:

    // native.def
    interface inimerse_native {
        /// Adds two integers.
        fn add(a: i32, b: i32) -> i32
        fn greet(name: string) -> string
        fn fail(code: i32) -> error
    }

    python3 tools/bindgen.py native.def --language c      --out build/bindings/c
    python3 tools/bindgen.py native.def --language java   --out build/bindings/java
    python3 tools/bindgen.py native.def --language python --out build/bindings/python

Supported types: i8/i16/i32/i64/u8/u16/u32/u64/f32/f64/bool/string/error,
array<T> of those.  Unsupported constructs (overloads, default parameters,
callbacks, async) are rejected with a precise error so types are checked at
generation time, not at link time.

Error convention (roadmap §2.2): every binding converts the Inimerse `error`
value into the target language's convention — C: int return (0 = success,
non-zero = error code); Java: InimerseException; Python: InimerseError.
"""
import argparse
import re
import sys
from pathlib import Path

SCALAR = {
    "i8": ("int8_t", "byte", "int"),
    "i16": ("int16_t", "short", "int"),
    "i32": ("int32_t", "int", "int"),
    "i64": ("int64_t", "long", "int"),
    "u8": ("uint8_t", "byte", "int"),
    "u16": ("uint16_t", "short", "int"),
    "u32": ("uint32_t", "int", "int"),
    "u64": ("uint64_t", "long", "int"),
    "f32": ("float", "float", "float"),
    "f64": ("double", "double", "float"),
    "bool": ("bool", "boolean", "bool"),
    "string": ("const char*", "String", "str"),
    "error": ("int", "int", "int"),
}
INT_RE = re.compile(r"^[iu](8|16|32|64)$")


class Fn:
    def __init__(self, name, params, ret, doc):
        self.name, self.params, self.ret, self.doc = name, params, ret, doc


class IdlError(Exception):
    pass


def parse_type(text, where):
    text = text.strip()
    m = re.fullmatch(r"array<(.+)>", text)
    if m:
        inner = m.group(1).strip()
        if inner not in SCALAR:
            raise IdlError(f"{where}: unsupported array element type '{inner}'")
        return ("array", inner)
    if text not in SCALAR:
        raise IdlError(f"{where}: unknown type '{text}' "
                       f"(supported: {', '.join(SCALAR)} or array<T>)")
    return ("scalar", text)


def parse_idl(text):
    fns, doc = [], []
    iface = None
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        where = f"line {lineno}"
        if not line or line.startswith("//") or line.startswith("#"):
            if line.startswith("///"):
                doc.append(line[3:].strip())
            continue
        m = re.match(r"interface\s+(\w+)\s*\{?\s*$", line)
        if m:
            iface = m.group(1)
            continue
        if line == "}":
            continue
        m = re.match(r"fn\s+(\w+)\s*\((.*)\)\s*(?:->\s*(.+?))?\s*$", line)
        if not m:
            raise IdlError(f"{where}: expected 'fn name(params) -> ret', got: {line}")
        name, params_src, ret_src = m.group(1), m.group(2).strip(), m.group(3)
        if any(f.name == name for f in fns):
            raise IdlError(f"{where}: duplicate function '{name}' (overloads not supported)")
        params = []
        if params_src:
            for i, p in enumerate(params_src.split(",")):
                pm = re.fullmatch(r"(\w+)\s*:\s*(.+)", p.strip())
                if not pm:
                    raise IdlError(f"{where} param {i+1}: expected 'name: type', got: {p.strip()}")
                if "=" in p:
                    raise IdlError(f"{where} param {i+1}: default parameters are not supported")
                params.append((pm.group(1), parse_type(pm.group(2), f"{where} param '{pm.group(1)}'")))
        ret = parse_type(ret_src, f"{where} return") if ret_src else None
        fns.append(Fn(name, params, ret, " ".join(doc) if doc else ""))
        doc = []
    if not iface:
        raise IdlError("missing 'interface <name> {' declaration")
    if not fns:
        raise IdlError("interface declares no functions")
    return iface, fns


def gen_c(iface, fns):
    guard = iface.upper() + "_H"
    h = [f"/* Generated by tools/bindgen.py — do not edit. C ABI bindings (roadmap §2.2).",
         f"   Error convention: 0 = success, non-zero = error code. */",
         f"#ifndef {guard}", f"#define {guard}", "",
         "#include <stdint.h>", "#include <stddef.h>", "", "#ifdef __cplusplus",
         'extern "C" {', "#endif", ""]
    for f in fns:
        if f.doc:
            h.append(f"/* {f.doc} */")
        params = []
        for pname, (kind, ty) in f.params:
            if kind == "scalar" and ty == "string":
                params.append(f"const char* {pname}, size_t {pname}_len")
            elif kind == "array":
                params.append(f"const {SCALAR[ty][0]}* {pname}, size_t {pname}_len")
            else:
                params.append(f"{SCALAR[ty][0]} {pname}")
        if f.ret and f.ret[0] == "scalar" and f.ret[1] not in ("string", "error", "bool"):
            params.append(f"{SCALAR[f.ret[1]][0]}* out")
        elif f.ret and f.ret[0] == "scalar" and f.ret[1] == "bool":
            params.append("bool* out")
        elif f.ret and f.ret[0] == "scalar" and f.ret[1] == "string":
            params.append("const char** out, size_t* out_len")
        h.append(f"int {iface}_{f.name}({', '.join(params) if params else 'void'});")
    h += ["", "#ifdef __cplusplus", "}", "#endif", "", f"#endif /* {guard} */", ""]
    return "\n".join(h)


def gen_java(iface, fns):
    cls = "".join(w.capitalize() for w in iface.split("_"))
    j = [f"// Generated by tools/bindgen.py — do not edit. JNI bridge (roadmap §3.2).",
         f"// Inimerse errors surface as InimerseException; checked exceptions are converted at the boundary.",
         f"public final class {cls} {{",
         "    static { System.loadLibrary(\"" + iface + "\"); }",
         "", "    /** Error raised when an Inimerse `error` crosses the native boundary. */",
         "    public static class InimerseException extends RuntimeException {",
         "        public final int code;",
         "        public InimerseException(int code, String message) { super(message); this.code = code; }",
         "    }", ""]
    for f in fns:
        if f.doc:
            j.append(f"    /** {f.doc} */")
        def jtype(k, t):
            if k == "scalar" and t == "string":
                return "String"
            base = SCALAR[t][1]
            return f"{base}[]" if k == "array" else base

        params = ", ".join(f"{jtype(k, t)} {p}" for p, (k, t) in f.params)
        ret = ("String" if f.ret and f.ret[0] == "scalar" and f.ret[1] == "string" else
               "int" if f.ret and f.ret[0] == "scalar" and f.ret[1] == "error" else
               (f"{SCALAR[f.ret[1][1]][1]}[]" if f.ret[0] == "array" else SCALAR[f.ret[1]][1])
               if f.ret else "void")
        j.append(f"    private static native {ret} native_{f.name}({params});")
        args = ", ".join(p for p, _ in f.params)
        call = f"native_{f.name}({args})"
        if f.ret and f.ret[1] == "error":
            j.append(f"    public static {ret} {f.name}({params}) {{")
            j.append(f"        int rc = {call};")
            j.append(f"        if (rc != 0) throw new InimerseException(rc, \"{f.name} failed\");")
            j.append("        return rc;")
            j.append("    }")
        else:
            body = call if ret == "void" else f"return {call}"
            j.append(f"    public static {ret} {f.name}({params}) {{ {body}; }}")
        j.append("")
    j.append("}")
    return "\n".join(j)


def gen_python(iface, fns):
    p = [f'"""Generated by tools/bindgen.py — do not edit. ctypes bridge (roadmap §3.3).',
         f"",
         f"Inimerse `error` values raise InimerseError at the boundary; async/await",
         f"callers can wrap these calls in asyncio.to_thread.""" + '"""',
         "import ctypes", "from ctypes import c_char_p, c_size_t, POINTER",
         "",
         f'_lib = ctypes.CDLL("lib{iface}.so")',
         "", "",
         "class InimerseError(RuntimeError):",
         '    """Raised when an Inimerse `error` crosses the native boundary."""',
         "    def __init__(self, code, fn_name):",
         "        super().__init__(f\"{fn_name} failed with error code {code}\")",
         "        self.code = code", ""]
    for f in fns:
        if f.doc:
            p.append(f'"""{f.doc}"""')
        ctypes_types = []
        for _, (kind, ty) in f.params:
            if kind == "scalar" and ty == "string":
                ctypes_types.append("c_char_p")
            elif kind == "array":
                ctypes_types.append(f"POINTER(c_{ty})")
            elif ty in ("f32", "f64"):
                ctypes_types.append("c_" + ty)
            elif ty == "bool":
                ctypes_types.append("c_bool")
            else:
                ctypes_types.append("c_int64" if ty in ("i64", "u64") else "c_int32")
        ret = f.ret[1] if f.ret else None
        if f.name == "fail" or ret == "error":
            p.append(f"def {f.name}(" + ", ".join(n for n, _ in f.params) + "):")
            p.append(f"    rc = _lib.{iface}_{f.name}(" + ", ".join(n for n, _ in f.params) + ")")
            p.append("    if rc != 0:")
            p.append(f"        raise InimerseError(rc, \"{f.name}\")")
            p.append("    return rc")
        else:
            p.append(f"_lib.{iface}_{f.name}.restype = "
                     + ("c_char_p" if ret == "string" else "c_int32"))
            p.append(f"def {f.name}(" + ", ".join(n for n, _ in f.params) + "):")
            args = ", ".join(
                f"{n}.encode()" if k == "scalar" and t == "string" else n
                for n, (k, t) in f.params)
            call = f"_lib.{iface}_{f.name}({args})"
            p.append(f"    return {call}.decode()" if ret == "string" else f"    return {call}")
        p.append("")
    return "\n".join(p)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("idl", help="interface definition (.def)")
    ap.add_argument("--language", required=True, choices=["c", "c++", "java", "python"])
    ap.add_argument("--out", required=True, help="output file path")
    args = ap.parse_args()

    src = Path(args.idl).read_text(encoding="utf-8")
    try:
        iface, fns = parse_idl(src)
    except IdlError as e:
        print(f"error: {args.idl}: {e}", file=sys.stderr)
        return 1

    gen = {"c": gen_c, "c++": gen_c, "java": gen_java, "python": gen_python}[args.language]
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(gen(iface, fns), encoding="utf-8")
    print(f"bindgen: {args.language} bindings for '{iface}' ({len(fns)} functions) -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
