#!/usr/bin/env python3
"""Python module scanner (v0.5 roadmap §3.3).

Identifies functions, classes, methods and decorators in Python sources and
emits a JSON inventory.  With `--emit-idl`, functions whose signatures are
fully type-annotated with convertible scalar types are converted into a
bindgen-compatible interface definition (tools/bindgen.py); dynamic parts
(untyped parameters, *args, decorators, async, generators) are reported as
manual adaptation points instead of being silently wrapped.

Usage:
    python3 tools/python_scan.py <files or dirs...> [--emit-idl out.def] [-o inventory.json]
"""
import argparse
import ast
import json
import sys
from pathlib import Path

ANN_MAP = {
    "int": "i32", "float": "f64", "bool": "bool",
}


def ann_to_idl(ann, warnings, where):
    """Convert a type annotation AST to a bindgen type (or None)."""
    if ann is None:
        return None
    if isinstance(ann, ast.Constant) and ann.value is None:
        return None  # -> None means void
    if isinstance(ann, ast.Name):
        return ANN_MAP.get(ann.id)
    if isinstance(ann, ast.Constant) and isinstance(ann.value, str):
        return ANN_MAP.get(ann.value)
    warnings.append(f"{where}: annotation '{ast.dump(ann)[:40]}' is not a convertible scalar")
    return None


def scan_file(path):
    warnings = []
    functions, classes = [], []
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except SyntaxError as e:
        return {"file": str(path), "functions": [], "classes": [],
                "warnings": [f"{path}: syntax error: {e}"]}

    def walk_body(body, prefix, depth):
        for node in body:
            where = f"{path}:{getattr(node, 'lineno', 0)}"
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                entry = {"name": prefix + node.name, "line": node.lineno,
                         "params": [], "ret": None, "decorators": [],
                         "async": isinstance(node, ast.AsyncFunctionDef)}
                for d in node.decorator_list:
                    entry["decorators"].append(ast.dump(d)[:60])
                    warnings.append(f"{where}: decorator on {node.name} must be inlined or "
                                    f"modeled as a higher-order function")
                if entry["async"]:
                    warnings.append(f"{where}: async def {node.name} maps to Inimerse "
                                    f"Result propagation or threads (manual)")
                returns = False
                for arg in node.args.args:
                    if arg.arg in ("self", "cls") and depth > 0:
                        continue
                    t = ann_to_idl(arg.annotation, warnings, f"{where} param {arg.arg}")
                    if t is None:
                        warnings.append(f"{where}: parameter '{arg.arg}' of {node.name} is "
                                        f"untyped (Python dynamic typing; manual)")
                        entry["params"].append((arg.arg, "?"))
                    else:
                        entry["params"].append((arg.arg, t))
                for arg in node.args.vararg, node.args.kwarg:
                    if arg is not None:
                        warnings.append(f"{where}: *args/**kwargs on {node.name} need "
                                        f"explicit signatures")
                if node.returns is not None:
                    rt = ann_to_idl(node.returns, warnings, f"{where} return")
                    entry["ret"] = rt
                    if rt is not None:
                        returns = True
                else:
                    warnings.append(f"{where}: {node.name} has no return annotation")
                functions.append(entry)
            elif isinstance(node, ast.ClassDef):
                classes.append({"name": prefix + node.name, "line": node.lineno,
                                "methods": [m.name for m in node.body
                                            if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef))]})
                warnings.append(f"{where}: class {node.name} maps to eidos/ed object syntax; "
                                f"methods need per-method review")
                walk_body(node.body, prefix + node.name + ".", depth + 1)

    walk_body(tree.body, "", 0)
    return {"file": str(path), "functions": functions, "classes": classes,
            "warnings": warnings}


def emit_idl(inventories, out_path):
    lines = ["// Generated by tools/python_scan.py --emit-idl (roadmap §3.3);",
             "// wrap with: python3 tools/bindgen.py out.def --language c|java|python",
             "interface python_bridge {"]
    count, skipped = 0, []
    for inv in inventories:
        for fn in inv["functions"]:
            if fn["async"] or fn["decorators"]:
                skipped.append(f"{fn['name']}: async/decorator")
                continue
            if any(t == "?" for _, t in fn["params"]):
                skipped.append(f"{fn['name']}: untyped parameters")
                continue
            if fn["ret"] is None and not fn["params"]:
                skipped.append(f"{fn['name']}: no typed signature (possible varargs)")
                continue
            params = ", ".join(f"{n}: {t}" for n, t in fn["params"])
            ret = f" -> {fn['ret']}" if fn["ret"] else ""
            lines.append(f"    fn {fn['name']}({params}){ret}")
            count += 1
    lines.append("}")
    Path(out_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return count, skipped


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("sources", nargs="+", help="files or directories")
    ap.add_argument("--emit-idl", help="write a bindgen .def for typed scalar functions")
    ap.add_argument("-o", "--output", help="write JSON inventory here (default: stdout)")
    args = ap.parse_args()

    files = []
    for s in args.sources:
        p = Path(s)
        if p.is_dir():
            files += [f for f in sorted(p.rglob("*")) if f.suffix == ".py" and not f.is_symlink()]
        elif p.is_file():
            files.append(p)
    if not files:
        sys.exit("error: no Python files found")

    inventories = []
    all_warnings = []
    for f in files:
        inv = scan_file(f)
        inventories.append(inv)
        all_warnings += inv["warnings"]

    payload = {"inventories": inventories, "warnings": all_warnings}
    report = json.dumps(payload, indent=2)
    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
        print(f"python_scan: {len(files)} files, {sum(len(i['functions']) for i in inventories)} functions, "
              f"{len(all_warnings)} warnings -> {args.output}")
    else:
        print(report)
    if args.emit_idl:
        count, skipped = emit_idl(inventories, args.emit_idl)
        print(f"python_scan: {count} functions -> {args.emit_idl}")
        for s in skipped:
            print(f"  skipped: {s}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
