'use strict';
const assert = require('node:assert/strict');
const { UppSession, STATES } = require('./upp_session');
const { hello, start, heartbeat, crash } = require('./upp_reference');
const manifest = { id:'demo', name:'Demo', version:'1.0.0', engine:'inimerse', entry:'main.im', abi:1 };
const s = new UppSession('host', manifest);
s.acceptHello(hello('client', manifest, ['heartbeat']));
assert.equal(s.apply(start('main.im')), STATES.RUNNING);
s.apply(heartbeat(1, 123)); assert.equal(s.snapshot().lastHeartbeat, 1); assert.equal(s.snapshot().lastHeartbeatAt, 123);
assert.equal(s.isHeartbeatStale(1000, 500), true); assert.equal(s.isHeartbeatStale(500, 500), false);
assert.throws(() => s.apply(heartbeat(0)), /out of order/);
assert.throws(() => s.apply(heartbeat(2, 100)), /timestamp out of order/);
assert.equal(s.checkHeartbeat(20000, 500), false); assert.equal(s.snapshot().state, STATES.CRASHED);
assert.equal(s.recover(), STATES.IDLE);
assert.equal(s.apply(start('main.im')), STATES.RUNNING);
assert.equal(s.apply(crash('boom')), STATES.CRASHED);
assert.throws(() => s.apply(start('main.im')), /cannot start/);
assert.equal(s.reset(), STATES.IDLE); assert.equal(s.snapshot().error, null); assert.throws(() => new UppSession('bad', manifest), /invalid role/);
console.log('UPP session tests: ok');
