'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const crypto = require('node:crypto');
const { validate, writeSignature, writeEd25519Signature } = require('./vverse_validate');
const d = fs.mkdtempSync(path.join(os.tmpdir(), 'vverse-')); fs.mkdirSync(path.join(d, 'assets')); fs.writeFileSync(path.join(d, 'manifest.json'), JSON.stringify({ id:'demo', version:'1.0.0', entry:'main.im' })); fs.writeFileSync(path.join(d, 'blueprint.json'), '{}'); fs.writeFileSync(path.join(d, 'main.im'), 'say "ok"');
const r = validate(d); assert.equal(r.valid, true); assert.ok(r.files['blueprint.json']); assert.ok(r.files['main.im']);
assert.throws(() => validate(d, { strictStructure: true }), /missing directory/);
for (const dir of ['laws', 'assets', 'mods', 'signatures']) fs.mkdirSync(path.join(d, dir), { recursive: true });
assert.equal(validate(d, { strictStructure: true }).valid, true);
fs.writeFileSync(path.join(d, 'manifest.json'), JSON.stringify({ id:'demo', version:'1.0.0', entry:'../escape.im' }));
assert.throws(() => validate(d), /escapes package/);
fs.writeFileSync(path.join(d, 'manifest.json'), JSON.stringify({ id:'demo', version:'1.0.0', entry:'main.im' }));
writeSignature(d);
const signed = validate(d, { requireSignature: true, requireCompleteSignature: true }); assert.equal(signed.signature['main.im'], r.files['main.im']);
const keys = crypto.generateKeyPairSync('ed25519');
const privateKey = path.join(d, 'signing-key.pem');
fs.writeFileSync(privateKey, keys.privateKey.export({ type: 'pkcs8', format: 'pem' }));
writeEd25519Signature(d, privateKey);
assert.equal(validate(d, { requirePublicSignature: true }).valid, true);
fs.writeFileSync(path.join(d, 'main.im'), 'say "tampered"');
assert.throws(() => validate(d, { requirePublicSignature: true }), /digest mismatch|signature verification failed/);
fs.writeFileSync(path.join(d, 'main.im'), 'say "ok"');
fs.writeFileSync(path.join(d, 'manifest.json'), JSON.stringify({ id:'changed', version:'1.0.0', entry:'main.im' }));
assert.throws(() => validate(d, { requireSignature: true }), /digest mismatch/);
fs.unlinkSync(path.join(d, 'blueprint.json')); assert.throws(() => validate(d), /blueprint/);
console.log('vverse validation tests: ok');
